export const SET_USER_LIST = "SET_USER_LIST"
//export const UPDATE_USER = "UPDATE_USER"
//export const DELETE_USER = "DELETE_USER"
//export const GET_USER = "GET_USER"
export const SET_USER = "SET_USER"
export const SET_TOKEN = "SET_TOKEN"
export const LOGOUT_USER = "LOGOUT_USER"